// This file is auto-generated. Each flashcard has a text front (from the filename) and an image back.
export const kriptovizsgaFlashcards = [
  { type: 'flashcard' as const, front: "Protokoll", back: `${import.meta.env.BASE_URL}kriptovizsga/protokoll.png`, frontIsImage: false, backIsImage: true },
  { type: 'flashcard' as const, front: "Szimmetrikus kulcsú titkosítás", back: `${import.meta.env.BASE_URL}kriptovizsga/szimmetrikus kulcsú titkosítás.png`, frontIsImage: false, backIsImage: true },
  { type: 'flashcard' as const, front: "Digitális aláírás", back: `${import.meta.env.BASE_URL}kriptovizsga/digitális aláírás.png`, frontIsImage: false, backIsImage: true },
  { type: 'flashcard' as const, front: "Kerchkoff-elvek", back: `${import.meta.env.BASE_URL}kriptovizsga/Kerchkoff-elvek.png`, frontIsImage: false, backIsImage: true },
  { type: 'flashcard' as const, front: "Támadók eszközei", back: `${import.meta.env.BASE_URL}kriptovizsga/támadók eszközei.png`, frontIsImage: false, backIsImage: true },
  { type: 'flashcard' as const, front: "Passzív támadások", back: `${import.meta.env.BASE_URL}kriptovizsga/passzív támadások.png`, frontIsImage: false, backIsImage: true },
  { type: 'flashcard' as const, front: "Aktív támadások", back: `${import.meta.env.BASE_URL}kriptovizsga/aktív támadások.png`, frontIsImage: false, backIsImage: true },
  { type: 'flashcard' as const, front: "Eltolásos rejtjel", back: `${import.meta.env.BASE_URL}kriptovizsga/eltolásos rejtjel.png`, frontIsImage: false, backIsImage: true },
  { type: 'flashcard' as const, front: "Monoalfabetikus helyettesítés", back: `${import.meta.env.BASE_URL}kriptovizsga/monoalfabetikus helyettesítés.png`, frontIsImage: false, backIsImage: true },
  { type: 'flashcard' as const, front: "Polialfabetikus eltolás - vigenere", back: `${import.meta.env.BASE_URL}kriptovizsga/polialfabetikus eltolás - vigenere.png`, frontIsImage: false, backIsImage: true },
  { type: 'flashcard' as const, front: "Biztonságos titkosítás", back: `${import.meta.env.BASE_URL}kriptovizsga/biztonságos titkosítás.png`, frontIsImage: false, backIsImage: true },
  { type: 'flashcard' as const, front: "Titkosítási séma", back: `${import.meta.env.BASE_URL}kriptovizsga/titkosítási séma.png`, frontIsImage: false, backIsImage: true },
  { type: 'flashcard' as const, front: "Tökéletes biztonság", back: `${import.meta.env.BASE_URL}kriptovizsga/tökéletes biztonság.png`, frontIsImage: false, backIsImage: true },
  { type: 'flashcard' as const, front: "One-time pad", back: `${import.meta.env.BASE_URL}kriptovizsga/one-time pad.png`, frontIsImage: false, backIsImage: true },
  { type: 'flashcard' as const, front: "Tétel a tökéletesen biztonságos titkosítási sémáról", back: `${import.meta.env.BASE_URL}kriptovizsga/tétel a tökéletesen biztonságos titkosítási sémáról.png`, frontIsImage: false, backIsImage: true },
  { type: 'flashcard' as const, front: "Modern kripto 3 alapelve", back: `${import.meta.env.BASE_URL}kriptovizsga/modern kripto 3 alapelve.png`, frontIsImage: false, backIsImage: true },
  { type: 'flashcard' as const, front: "Kolmogorov bonyolultság és algoritmikus véletlenség", back: `${import.meta.env.BASE_URL}kriptovizsga/kolmogorov bonyolultság és algoritmikus véletlenség.png`, frontIsImage: false, backIsImage: true },
  { type: 'flashcard' as const, front: "Probabilisztikus polinom idejű hatékony támadó", back: `${import.meta.env.BASE_URL}kriptovizsga/probabilisztikus polinom idejű hatékony támadó.png`, frontIsImage: false, backIsImage: true },
  { type: 'flashcard' as const, front: "Elhanyagolható függvéy", back: `${import.meta.env.BASE_URL}kriptovizsga/elhanyagolható függvéy.png`, frontIsImage: false, backIsImage: true },
  { type: 'flashcard' as const, front: "Számítási biztonság", back: `${import.meta.env.BASE_URL}kriptovizsga/számítási biztonság.png`, frontIsImage: false, backIsImage: true },
  { type: 'flashcard' as const, front: "Redukciós bizonyítások", back: `${import.meta.env.BASE_URL}kriptovizsga/redukciós bizonyítások.png`, frontIsImage: false, backIsImage: true },
  { type: 'flashcard' as const, front: "Titkosítási séma 2", back: `${import.meta.env.BASE_URL}kriptovizsga/titkosítási séma 2.png`, frontIsImage: false, backIsImage: true },
  { type: 'flashcard' as const, front: "Megkülönböztethetetlenség egyszeres lehallgatás", back: `${import.meta.env.BASE_URL}kriptovizsga/megkülönböztethetetlenség egyszeres lehallgatás.png`, frontIsImage: false, backIsImage: true },
  { type: 'flashcard' as const, front: "Next-bit teszt", back: `${import.meta.env.BASE_URL}kriptovizsga/next-bit teszt.png`, frontIsImage: false, backIsImage: true },
  { type: 'flashcard' as const, front: "Folyamtitkosító", back: `${import.meta.env.BASE_URL}kriptovizsga/folyamtitkosító.png`, frontIsImage: false, backIsImage: true },
  { type: 'flashcard' as const, front: "Megkülönböztethetetlenség többszörös lehallgatás", back: `${import.meta.env.BASE_URL}kriptovizsga/megkülönböztethetetlenség többszörös lehallgatás.png`, frontIsImage: false, backIsImage: true },
  { type: 'flashcard' as const, front: "Megkülönböztethetetlenség cpa", back: `${import.meta.env.BASE_URL}kriptovizsga/megkülönböztethetetlenség cpa.png`, frontIsImage: false, backIsImage: true },
  { type: 'flashcard' as const, front: "Blokktitkosító", back: `${import.meta.env.BASE_URL}kriptovizsga/blokktitkosító.png`, frontIsImage: false, backIsImage: true },
  { type: 'flashcard' as const, front: "Feistel hálózat", back: `${import.meta.env.BASE_URL}kriptovizsga/feistel hálózat.png`, frontIsImage: false, backIsImage: true },
  { type: 'flashcard' as const, front: "DES", back: `${import.meta.env.BASE_URL}kriptovizsga/DES.png`, frontIsImage: false, backIsImage: true },
  { type: 'flashcard' as const, front: "S-p hálózat", back: `${import.meta.env.BASE_URL}kriptovizsga/s-p hálózat.png`, frontIsImage: false, backIsImage: true },
  { type: 'flashcard' as const, front: "Megkülönböztethetetlenség cca", back: `${import.meta.env.BASE_URL}kriptovizsga/megkülönböztethetetlenség cca.png`, frontIsImage: false, backIsImage: true },
  { type: 'flashcard' as const, front: "Hash függvény és hozzá tartozó definíciók", back: `${import.meta.env.BASE_URL}kriptovizsga/hash függvény és hozzá tartozó definíciók.png`, frontIsImage: false, backIsImage: true },
  { type: 'flashcard' as const, front: "Születésnap támadás", back: `${import.meta.env.BASE_URL}kriptovizsga/születésnap támadás.png`, frontIsImage: false, backIsImage: true },
  { type: 'flashcard' as const, front: "MAC", back: `${import.meta.env.BASE_URL}kriptovizsga/MAC.png`, frontIsImage: false, backIsImage: true },
  { type: 'flashcard' as const, front: "MAC biztonság", back: `${import.meta.env.BASE_URL}kriptovizsga/MAC biztonság.png`, frontIsImage: false, backIsImage: true },
  { type: 'flashcard' as const, front: "Rögzített hosszú MAC", back: `${import.meta.env.BASE_URL}kriptovizsga/rögzített hosszú MAC.png`, frontIsImage: false, backIsImage: true },
  { type: 'flashcard' as const, front: "CBC-MAC", back: `${import.meta.env.BASE_URL}kriptovizsga/CBC-MAC.png`, frontIsImage: false, backIsImage: true },
  { type: 'flashcard' as const, front: "Encrypt then mac ETM", back: `${import.meta.env.BASE_URL}kriptovizsga/encrypt then mac ETM.png`, frontIsImage: false, backIsImage: true },
  { type: 'flashcard' as const, front: "Encrypt and mac E&M", back: `${import.meta.env.BASE_URL}kriptovizsga/encrypt and mac E&M.png`, frontIsImage: false, backIsImage: true },
  { type: 'flashcard' as const, front: "Mac then encrypt MTE", back: `${import.meta.env.BASE_URL}kriptovizsga/mac then encrypt MTE.png`, frontIsImage: false, backIsImage: true },
  { type: 'flashcard' as const, front: "Nyílvános kulcsú titkosítási séma", back: `${import.meta.env.BASE_URL}kriptovizsga/nyílvános kulcsú titkosítási séma.png`, frontIsImage: false, backIsImage: true },
  { type: 'flashcard' as const, front: "Hibrid titkosítás", back: `${import.meta.env.BASE_URL}kriptovizsga/hibrid titkosítás.png`, frontIsImage: false, backIsImage: true },
  { type: 'flashcard' as const, front: "Textbook RSA", back: `${import.meta.env.BASE_URL}kriptovizsga/textbook RSA.png`, frontIsImage: false, backIsImage: true },
  { type: 'flashcard' as const, front: "Randomizált RSA", back: `${import.meta.env.BASE_URL}kriptovizsga/randomizált RSA.png`, frontIsImage: false, backIsImage: true },
  { type: 'flashcard' as const, front: "Csoport", back: `${import.meta.env.BASE_URL}kriptovizsga/csoport.png`, frontIsImage: false, backIsImage: true },
  { type: 'flashcard' as const, front: "DLOG feladat", back: `${import.meta.env.BASE_URL}kriptovizsga/DLOG feladat.png`, frontIsImage: false, backIsImage: true },
  { type: 'flashcard' as const, front: "Diffie-Hellman kulcscsere", back: `${import.meta.env.BASE_URL}kriptovizsga/Diffie-Hellman kulcscsere.png`, frontIsImage: false, backIsImage: true },
  { type: 'flashcard' as const, front: "Diffie-Hellman CDH DDH", back: `${import.meta.env.BASE_URL}kriptovizsga/Diffie-Hellman CDH DDH.png`, frontIsImage: false, backIsImage: true },
  { type: 'flashcard' as const, front: "Elgamal titkosítás", back: `${import.meta.env.BASE_URL}kriptovizsga/elgamal titkosítás.png`, frontIsImage: false, backIsImage: true },
  { type: 'flashcard' as const, front: "Elgamal aláírás", back: `${import.meta.env.BASE_URL}kriptovizsga/elgamal aláírás.png`, frontIsImage: false, backIsImage: true },
  { type: 'flashcard' as const, front: "Hashed RSA aláírás", back: `${import.meta.env.BASE_URL}kriptovizsga/hashed RSA aláírás.png`, frontIsImage: false, backIsImage: true },
  { type: 'flashcard' as const, front: "Textbook RSA aláírás", back: `${import.meta.env.BASE_URL}kriptovizsga/textbook RSA aláírás.png`, frontIsImage: false, backIsImage: true },
  { type: 'flashcard' as const, front: "Aláírás séma biztonsága", back: `${import.meta.env.BASE_URL}kriptovizsga/aláírás séma biztonsága.png`, frontIsImage: false, backIsImage: true },
  { type: 'flashcard' as const, front: "Digitális aláírás vs mac", back: `${import.meta.env.BASE_URL}kriptovizsga/digitális aláírás vs mac.png`, frontIsImage: false, backIsImage: true },
];
