// This file contains the questions for the Numerical Methods Vizsga quiz as an array.
export const nummod1Questions = [
  "1. Definiálja a gépi számok halmazát (a tanult modellnek megfelelően)! Adja meg a normalizált lebegőpontos szám alakját!",
  "2. Írja le a gépi számhalmaz nevezetes számait!",
  "3. Definiálja az input függvény fogalmát, és írja le a hibájára vonatkozó tételt!",
  "4. Adja meg a hibaszámítás alapfogalmait: hiba, abszolút-, relatív hiba és korlátjaik!",
  "5. Írja le az alapműveletek abszolút hibakorlátjaira vonatkozó képleteket!",
  "6. Írja le az alapműveletek relatív hibakorlátjaira vonatkozó képleteket!",
  "7. Írja le a függvényérték abszolút hibakorlátjára vonatkozó összefüggést!",
  "8. Írja le a függvényérték abszolút és relatív hibakorlátjára vonatkozó összefüggést (feltételezve, hogy a függvény kétszer folytonosan deriválható)!",
  "9. Definiálja az f függvény pontbeli kondíciószámát!",
  "10. Mennyi a Gauss-elimináció, illetve a visszahelyettesítés műveletigénye? (x + O(n^y))",
  "11. Írja fel az Lₖ mátrixot, melyet A^(k−1)-re alkalmazva a Gauss-elimináció egy lépését kapjuk!",
  "12. Adjon elégséges feltételt az LU-felbontás létezésére! (Gauss-eliminációval)",
  "13. Adjon elégséges feltételt az LU-felbontás létezésére és egyértelműségére! (Gauss-elimináció nélkül)",
  "14. Mennyi az LU-felbontás, illetve egy háromszög mátrixú LER megoldásának műveletigénye? (x + O(n^y))",
  "15. Mikor nevezzük A-t szimmetrikus és pozitív definit mátrixnak?",
  "16. Mikor nevezzük A-t a soraira (oszlopaira) nézve szigorúan diagonálisan dominánsnak?",
  "17. Definiálja A fél sávszélességét!",
  "18. Definiálja A profilját!",
  "19. Definiálja az A mátrix A₁₁-re vonatkozó Schur-komplementjét!",
  "20. Mondja ki a Gauss-elimináció (legalább) 4 tulajdonságának megmaradási tételét!",
  "21. Definiálja a Cholesky-felbontást!",
  "22. Milyen tételt tanult a Cholesky-felbontásról?",
  "23. Mennyi a Cholesky-felbontás, illetve egy háromszög mátrixú LER megoldásának műveletigénye? (x + O(n^y))",
  "24. Milyen tételt tanult a QR-felbontásról?",
  "25. Mennyi a QR-felbontás műveletigénye?",
  "26. Definiálja a Householder-mátrixot!",
  "27. Írja le a Householder-transzformáció 4 tanult tulajdonságát!",
  "28. Adja meg azt a Householder-mátrixot, melyre az azonos hosszúságú a ≠ b vektorok esetén Ha = b!",
  "29. Írja le a vektornorma definícióját és tulajdonságait!",
  "30. Írja le a mátrixnorma definícióját és tulajdonságait!",
  "31. Írja le az indukált mátrixnormáról tanult tételt!",
  "32. Mit jelent az illeszkedés normák esetén?",
  "33. Írja le az 1, 2, ∞ és Frobenius mátrixnormát!",
  "34. Mit nevezünk egy mátrix spektrálsugarának?",
  "35. Definiálja a kondíciószámot mátrixok esetén! Mikor értelmezhető?",
  "36. Írja le a LER jobboldalának változásakor érvényes perturbációs tételt!",
  "37. Írja le a LER mátrixának változásakor érvényes perturbációs tételt!",
  "38. Definiálja a reziduumvektort (maradékvektort)!",
  "39. Definiálja a relatív maradékot!",
  "40. Írja le a relatív maradékról tanult két állítást!",
  "41. Írja le a kondíciószám (legalább) 4 tulajdonságát!",
  "42. Írja le a kontrakció fogalmát φ: ℝⁿ → ℝⁿ függvény esetén!",
  "43. Írja le a Banach-féle fixponttételt ℝⁿ-re!",
  "44. Adjon elégséges feltételt az x^(k+1) = Bx^(k) + c alakú iterációk konvergenciájára!",
  "45. Írja le az indukált normák és spektrálsugár kapcsolatáról tanult lemmát!",
  "46. Adjon szükséges és elégséges feltételt az x^(k+1) = Bx^(k) + c iterációk konvergenciájára!",
  "47. Írja le a Jacobi- és a csillapított Jacobi-iterációt!",
  "48. Adjon elégséges feltételt a Jacobi- és csillapított Jacobi-iteráció konvergenciájára!",
  "49. Írja le a Gauss–Seidel-iterációt (a koordinátás alakot is)!",
  "50. Írja le a Gauss–Seidel relaxációs módszert (a koordinátás alakot is)!",
  "51. Milyen szükséges és elégséges feltételt tanult a Gauss–Seidel relaxáció konvergenciájáról?",
  "52. Szigorúan diagonálisan domináns mátrix esetén mit tud mondani a Jacobi- és a Gauss–Seidel-iteráció konvergenciájáról?",
  "53. Milyen tételt tanult szimmetrikus, pozitív definit és tridiagonális mátrixok esetén a J(1), S(1), S(ω) módszerekről?",
  "54. Vezesse le a Richardson-típusú iterációk alakját!",
  "55. Milyen tételt tanult a Richardson-típusú iterációkról?",
  "56. Definiálja a J pozícióhalmazra illeszkedő részleges LU-felbontást!",
  "57. Írja le az ILU-felbontás algoritmusát (L, U és Q előállításának felírása)!",
  "58. Adjon elégséges feltételt az ILU-felbontás létezésére és egyértelműségére!",
  "59. Vezesse le az ILU-algoritmust! A reziduumvektor bevezetésével írja fel a gyakorlatban használt alakot is!",
  "60. Írja le a Bolzano-tételt!",
  "61. Írja le az intervallumfelezés algoritmusát és hibabecslését!",
  "62. Írja le a Brouwer-féle fixponttételt!",
  "63. Írja le a fixponttételt az [a; b] intervallumra!",
  "64. Adjon meg elégséges feltételt a kontrakcióra!",
  "65. Definiálja a konvergencia rend fogalmát!",
  "66. Írja le az m-ed rendű konvergenciára vonatkozó tételt!",
  "67. Vezesse le a Newton-módszer képletét!",
  "68. Írja le a Newton-módszer monoton konvergenciatételét!",
  "69. Írja le a Newton-módszer lokális konvergenciatételét!",
  "70. Definiálja a húr-módszert!",
  "71. Definiálja a szelő-módszert!",
  "72. Írja le a szelő-módszer lokális konvergenciatételét!",
  "73. Vezesse le a többváltozós Newton-módszer képletét!",
  "74. Milyen becslést tanult polinomok gyökeinek elhelyezkedéséről?",
  "75. Írja le a polinom helyettesítési értékeinek gyors számolására tanult Horner-algoritmust!"
];
